version: '3.8'
services:
  vprodb:
    build:
      #for building the db image 
      context: ./Docker-files/db
    image: 40075793/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
#check the application.properties file for image names and env variables
  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build: 
      context: ./Docker-files/app
    image: 40075793/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
    
  vproweb:
    build: 
      context: ./Docker-files/web
    image: 40075793/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"
#{} means it will create the volumes first than start building images when we run this file
volumes:
   vprodbdata: {}
   vproappdata: {}
  